# Generated by Django 5.2.17 on 2026-08-21 14:08

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0002_remove_finding_audit_finding_status_ck_and_more'),
        ('documents', '0002_document_process'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootCauseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('five_whys', 'Cinco porqués'), ('ishikawa', 'Ishikawa'), ('pareto', 'Pareto'), ('other', 'Otro método documentado')], max_length=30)),
                ('analysis', models.TextField()),
                ('conclusion', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_cause_analyses_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='root_cause_analysis', to='audits.finding')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_cause_analyses_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'improvements_root_cause_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En revisión'), ('in_progress', 'En ejecución'), ('in_verification', 'En verificación'), ('closed', 'Cerrada'), ('reopened', 'Reabierta'), ('cancelled', 'Cancelada')], default='pending', max_length=30)),
                ('effectiveness_criterion', models.TextField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions_approved', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='audits.finding')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('root_cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrective_actions', to='improvements.rootcauseanalysis')),
            ],
            options={
                'db_table': 'improvements_corrective_action',
                'ordering': ['due_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ActionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_evidence_links', to='documents.fileasset')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='improvements.correctiveaction')),
            ],
            options={
                'db_table': 'improvements_action_evidence',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('action', 'file_asset'), name='improvement_action_evidence_uq'), models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='improvement_evidence_text_ck')],
            },
        ),
        migrations.CreateModel(
            name='EffectivenessReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('effective', 'Eficaz'), ('ineffective', 'No eficaz')], max_length=20)),
                ('notes', models.TextField()),
                ('reopens_action', models.BooleanField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effectiveness_reviews', to='improvements.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effectiveness_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'improvements_effectiveness_review',
                'ordering': ['-reviewed_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('result__in', ['effective', 'ineffective'])), name='improvement_review_result_ck'), models.CheckConstraint(condition=models.Q(models.Q(('reopens_action', False), ('result', 'effective')), models.Q(('reopens_action', True), ('result', 'ineffective')), _connector='OR'), name='improvement_review_reopen_ck'), models.CheckConstraint(condition=models.Q(('notes', ''), _negated=True), name='improvement_review_notes_ck')],
            },
        ),
        migrations.AddConstraint(
            model_name='rootcauseanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['five_whys', 'ishikawa', 'pareto', 'other'])), name='improvement_root_method_ck'),
        ),
        migrations.AddConstraint(
            model_name='rootcauseanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved'])), name='improvement_root_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='rootcauseanalysis',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('analysis', ''), _negated=True), models.Q(('conclusion', ''), _negated=True)), name='improvement_root_text_ck'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['status', 'due_date', 'owner'], name='improvement_action_alert_ix'),
        ),
        migrations.AddConstraint(
            model_name='correctiveaction',
            constraint=models.UniqueConstraint(models.F('finding'), django.db.models.functions.text.Lower('code'), name='improvement_action_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='correctiveaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'in_review', 'in_progress', 'in_verification', 'closed', 'reopened', 'cancelled'])), name='improvement_action_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='correctiveaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('description', ''), _negated=True), models.Q(('effectiveness_criterion', ''), _negated=True)), name='improvement_action_text_ck'),
        ),
    ]
