# Generated by Django 5.2.17 on 2026-08-21 03:51

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicators_deactivated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_indicators', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='processes.process')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indicators_indicator',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('dimension_key', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_observations', to='imports.importjob')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='indicators.indicator')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_observations', to='organizations.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_observations', to='organizations.site')),
                ('source_row', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_observation', to='imports.importrow')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indicators_observation',
                'ordering': ['indicator__code', 'period_start', 'dimension_key'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobada'), ('effective', 'Vigente'), ('superseded', 'Sustituida'), ('annulled', 'Anulada')], max_length=30)),
                ('purpose', models.TextField()),
                ('unit', models.CharField(max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('annual', 'Anual')], max_length=20)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Mayor es mejor'), ('lower_is_better', 'Menor es mejor'), ('target_is_best', 'Objetivo exacto')], max_length=30)),
                ('formula_ast', models.JSONField()),
                ('formula_hash', models.CharField(max_length=64)),
                ('target_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='indicators.indicator')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_versions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_versions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'indicators_indicator_version',
                'ordering': ['indicator__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('performance_status', models.CharField(choices=[('on_target', 'En meta'), ('warning', 'Advertencia'), ('off_target', 'Fuera de meta'), ('not_evaluated', 'Sin evaluación')], max_length=30)),
                ('status', models.CharField(choices=[('calculated', 'Calculado'), ('in_review', 'En revisión'), ('rejected', 'Rechazado'), ('published', 'Publicado'), ('corrected', 'Corregido')], max_length=30)),
                ('calculated_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('result_hash', models.CharField(max_length=64, unique=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_results_calculated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_results_published', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_results_reviewed', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_results', to='organizations.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_results', to='organizations.site')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='indicators.indicatorresult')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('indicator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='indicators.indicatorversion')),
            ],
            options={
                'db_table': 'indicators_result',
                'ordering': ['indicator_version__indicator__code', '-period_start', '-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_role', models.CharField(max_length=30)),
                ('position', models.PositiveIntegerField()),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_inputs', to='indicators.indicatorobservation')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inputs', to='indicators.indicatorresult')),
            ],
            options={
                'db_table': 'indicators_result_input',
                'ordering': ['input_role', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['organization', 'process', 'is_active', 'code'], name='indicator_catalog_ix'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='indicator_scope_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('deactivation_reason', ''), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False), models.Q(('deactivation_reason', ''), _negated=True)), _connector='OR'), name='indicator_lifecycle_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicator',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='indicator_text_ck'),
        ),
        migrations.AddIndex(
            model_name='indicatorobservation',
            index=models.Index(fields=['indicator', 'period_start', 'period_end'], name='indicator_obs_period_ix'),
        ),
        migrations.AddIndex(
            model_name='indicatorobservation',
            index=models.Index(fields=['site', 'service', 'period_start'], name='indicator_observation_scope_ix'),
        ),
        migrations.AddConstraint(
            model_name='indicatorobservation',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='indicator_observation_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorobservation',
            constraint=models.CheckConstraint(condition=models.Q(('dimension_key', ''), _negated=True), name='indicator_observation_dimension_ck'),
        ),
        migrations.AddIndex(
            model_name='indicatorversion',
            index=models.Index(fields=['indicator', 'status', '-version_no'], name='indicator_version_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.UniqueConstraint(fields=('indicator', 'version_no'), name='indicator_version_no_uq'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='indicator_version_no_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'effective', 'superseded', 'annulled'])), name='indicator_version_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.CheckConstraint(condition=models.Q(('formula_hash__regex', '^[0-9a-f]{64}$')), name='indicator_formula_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='indicator_version_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', ''), _negated=True), models.Q(('unit', ''), _negated=True)), name='indicator_version_text_ck'),
        ),
        migrations.AddIndex(
            model_name='indicatorresult',
            index=models.Index(fields=['indicator_version', 'period_start', 'status'], name='indicator_result_period_ix'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='indicator_result_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['calculated', 'in_review', 'rejected', 'published', 'corrected'])), name='indicator_result_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(('performance_status__in', ['on_target', 'warning', 'off_target', 'not_evaluated'])), name='indicator_performance_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(('result_hash__regex', '^[0-9a-f]{64}$')), name='indicator_result_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status__in', ['published', 'corrected'])), models.Q(models.Q(('status__in', ['published', 'corrected']), _negated=True), ('published_at__isnull', True), ('published_by__isnull', True)), _connector='OR'), name='indicator_result_publication_ck'),
        ),
        migrations.AddConstraint(
            model_name='indicatorresult',
            constraint=models.CheckConstraint(condition=models.Q(('supersedes', models.F('id')), _negated=True), name='indicator_result_not_self_ck'),
        ),
        migrations.AddConstraint(
            model_name='resultinput',
            constraint=models.UniqueConstraint(fields=('result', 'observation'), name='indicator_result_observation_uq'),
        ),
        migrations.AddConstraint(
            model_name='resultinput',
            constraint=models.UniqueConstraint(fields=('result', 'input_role', 'position'), name='indicator_result_role_position_uq'),
        ),
        migrations.AddConstraint(
            model_name='resultinput',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='indicator_result_input_position_ck'),
        ),
        migrations.AddConstraint(
            model_name='resultinput',
            constraint=models.CheckConstraint(condition=models.Q(('input_role', ''), _negated=True), name='indicator_result_input_role_ck'),
        ),
    ]
