# Generated by Django 5.2.17 on 2026-08-28 01:12

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_document_process"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("version_no", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("dashboard", "Tablero de indicadores"),
                            ("indicator_results", "Resultados KPI"),
                            ("risks", "Riesgos y controles"),
                            ("findings", "Hallazgos"),
                            ("corrective_actions", "Acciones correctivas"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV UTF-8"), ("xlsx", "Excel XLSX"), ("pdf", "PDF")],
                        max_length=10,
                    ),
                ),
                (
                    "consumer",
                    models.CharField(
                        choices=[
                            ("general", "Consulta general"),
                            ("power_bi_desktop", "Power BI Desktop"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("schema_definition", models.JSONField()),
                ("schema_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("superseded", "Sustituido"),
                            ("annulled", "Anulado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_contracts_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_export_contract",
                "ordering": ["code", "-version_no"],
            },
        ),
        migrations.CreateModel(
            name="ExportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filters", models.JSONField(default=dict)),
                ("row_count", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField()),
                ("output_hash", models.CharField(max_length=64)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="reports.exportcontract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="export_runs",
                        to="documents.fileasset",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_export_run",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exportcontract",
            index=models.Index(
                fields=["status", "dataset", "format"], name="report_contract_catalog_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("version_no"),
                name="report_contract_code_version_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_no__gte", 1)), name="report_contract_version_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "published", "superseded", "annulled"])
                ),
                name="report_contract_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "dataset__in",
                        [
                            "dashboard",
                            "indicator_results",
                            "risks",
                            "findings",
                            "corrective_actions",
                        ],
                    )
                ),
                name="report_contract_dataset_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("format__in", ["csv", "xlsx", "pdf"])),
                name="report_contract_format_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumer__in", ["general", "power_bi_desktop"])),
                name="report_contract_consumer_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_hash__regex", "^[0-9a-f]{64}$")),
                name="report_contract_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("status", "published"),
                    ),
                    models.Q(("status", "published"), _negated=True),
                    _connector="OR",
                ),
                name="report_contract_publication_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcontract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("code", ""), _negated=True), models.Q(("name", ""), _negated=True)
                ),
                name="report_contract_text_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(
                fields=["requested_by", "-generated_at"], name="report_run_requester_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="exportrun",
            index=models.Index(fields=["contract", "-generated_at"], name="report_run_contract_ix"),
        ),
        migrations.AddConstraint(
            model_name="exportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("row_count__gte", 0)), name="report_run_rows_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="exportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_hash__regex", "^[0-9a-f]{64}$")),
                name="report_run_hash_ck",
            ),
        ),
    ]
