# Generated by Django 5.2.17 on 2026-08-21 04:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_process'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('scope', models.TextField()),
                ('criteria', models.TextField()),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('in_progress', 'En ejecución'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_plans_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_audit_plans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_plans', to='organizations.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_plans_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_audit_plan',
                'ordering': ['-planned_start', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AuditExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'En ejecución'), ('in_review', 'En revisión'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_executions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_executions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('audit_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='audits.auditplan')),
            ],
            options={
                'db_table': 'audits_audit_execution',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_checklists_deactivated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_checklists', to='organizations.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_checklist',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('criterion', models.TextField()),
                ('response_type', models.CharField(choices=[('compliance', 'Conforme / no conforme'), ('observation', 'Observación descriptiva')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_checklist_item',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AuditResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('conform', 'Conforme'), ('nonconform', 'No conforme'), ('not_applicable', 'No aplica'), ('observation', 'Observación')], max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='audits.auditexecution')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_responses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='audits.checklistitem')),
            ],
            options={
                'db_table': 'audits_audit_response',
                'ordering': ['checklist_item__position'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('effective', 'Vigente'), ('superseded', 'Sustituida'), ('annulled', 'Anulada')], max_length=30)),
                ('version_hash', models.CharField(max_length=64)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_checklist_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='audits.checklist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_checklist_versions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_checklist_version',
                'ordering': ['checklist__code', '-version_no'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='audits.checklistversion'),
        ),
        migrations.AddField(
            model_name='auditexecution',
            name='checklist_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='audits.checklistversion'),
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('finding_type', models.CharField(choices=[('observation', 'Observación'), ('opportunity', 'Oportunidad de mejora'), ('nonconformity', 'No conformidad')], max_length=30)),
                ('criterion', models.TextField()),
                ('condition', models.TextField()),
                ('impact', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_analysis', 'En análisis'), ('cancelled', 'Cancelado')], default='open', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('evidence_absence_reason', models.CharField(blank=True, max_length=500)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('audit_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audits.auditresponse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='audits.auditexecution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_audit_findings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_finding',
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_evidence_links', to='documents.fileasset')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='audits.finding')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audits_finding_evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditplan',
            index=models.Index(fields=['organization', 'status', 'planned_start'], name='audit_plan_catalog_ix'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='audit_plan_scope_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.CheckConstraint(condition=models.Q(('planned_end__gte', models.F('planned_start'))), name='audit_plan_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'in_progress', 'completed', 'cancelled'])), name='audit_plan_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='auditplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('scope', ''), _negated=True), models.Q(('criteria', ''), _negated=True)), name='audit_plan_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='audit_checklist_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='checklist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('deactivation_reason', ''), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False), models.Q(('deactivation_reason', ''), _negated=True)), _connector='OR'), name='audit_checklist_lifecycle_ck'),
        ),
        migrations.AddConstraint(
            model_name='auditresponse',
            constraint=models.UniqueConstraint(fields=('execution', 'checklist_item'), name='audit_response_item_uq'),
        ),
        migrations.AddConstraint(
            model_name='auditresponse',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['conform', 'nonconform', 'not_applicable', 'observation'])), name='audit_response_result_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.UniqueConstraint(fields=('checklist', 'version_no'), name='audit_checklist_version_uq'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='audit_checklist_version_no_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_hash__regex', '^[0-9a-f]{64}$')), name='audit_checklist_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklistversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='audit_checklist_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(fields=('checklist_version', 'position'), name='audit_checklist_item_pos_uq'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='audit_checklist_item_pos_ck'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('criterion', ''), _negated=True), name='audit_checklist_item_text_ck'),
        ),
        migrations.AddIndex(
            model_name='auditexecution',
            index=models.Index(fields=['audit_plan', 'status'], name='audit_execution_plan_ix'),
        ),
        migrations.AddConstraint(
            model_name='auditexecution',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='audit_execution_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='auditexecution',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'in_review', 'completed', 'cancelled'])), name='audit_execution_status_ck'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'impact', 'due_date'], name='audit_finding_alert_ix'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('execution', 'code'), name='audit_finding_execution_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('finding_type__in', ['observation', 'opportunity', 'nonconformity'])), name='audit_finding_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('impact__in', ['low', 'medium', 'high', 'critical'])), name='audit_finding_impact_ck'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_analysis', 'cancelled'])), name='audit_finding_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('criterion', ''), _negated=True), models.Q(('condition', ''), _negated=True)), name='audit_finding_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='findingevidence',
            constraint=models.UniqueConstraint(fields=('finding', 'file_asset'), name='audit_finding_evidence_uq'),
        ),
        migrations.AddConstraint(
            model_name='findingevidence',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='audit_finding_evidence_text_ck'),
        ),
    ]
