# Generated by Django 5.2.17 on 2026-08-21 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finding',
            name='audit_finding_status_ck',
        ),
        migrations.AlterField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_analysis', 'En análisis'), ('with_plan', 'Con plan'), ('in_verification', 'En verificación'), ('closed', 'Cerrado'), ('reopened', 'Reabierto'), ('cancelled', 'Cancelado')], default='open', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_analysis', 'with_plan', 'in_verification', 'closed', 'reopened', 'cancelled'])), name='audit_finding_status_ck'),
        ),
    ]
