# Generated by Django 5.2.17 on 2026-08-21 02:04

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("strategic", "Estratégico"),
                            ("operational", "Operativo"),
                            ("support", "Soporte"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes_process_deactivated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_processes",
                        to="organizations.area",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processes_process",
                "ordering": ["process_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="ProcessVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_no", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_review", "En revisión"),
                            ("approved", "Aprobado"),
                            ("effective", "Vigente"),
                            ("superseded", "Sustituido"),
                            ("annulled", "Anulado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("objective", models.TextField()),
                ("scope", models.TextField()),
                ("version_hash", models.CharField(max_length=64)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="processes.process",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_versions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="process_versions_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processes_process_version",
                "ordering": ["process__code", "-version_no"],
            },
        ),
        migrations.CreateModel(
            name="SipocEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("supplier", "Proveedor"),
                            ("input", "Entrada"),
                            ("activity", "Actividad"),
                            ("output", "Salida"),
                            ("customer", "Cliente"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sipoc_entries",
                        to="processes.processversion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "processes_sipoc_entry",
                "ordering": ["entry_type", "position"],
            },
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["organization", "process_type", "is_active", "code"],
                name="process_catalog_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(fields=["owner_area", "is_active"], name="process_owner_ix"),
        ),
        migrations.AddConstraint(
            model_name="process",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("code"),
                name="process_scope_code_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="process",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deactivated_at__isnull", True),
                        ("deactivated_by__isnull", True),
                        ("deactivation_reason", ""),
                        ("is_active", True),
                    ),
                    models.Q(
                        ("deactivated_at__isnull", False),
                        ("deactivated_by__isnull", False),
                        ("is_active", False),
                        models.Q(("deactivation_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="process_lifecycle_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="process",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("code", ""), _negated=True), models.Q(("name", ""), _negated=True)
                ),
                name="process_required_text_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="process",
            constraint=models.CheckConstraint(
                condition=models.Q(("process_type__in", ["strategic", "operational", "support"])),
                name="process_type_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="processversion",
            index=models.Index(
                fields=["process", "status", "-version_no"], name="process_version_state_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.UniqueConstraint(
                fields=("process", "version_no"), name="process_version_no_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_no__gte", 1)), name="process_version_no_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "in_review", "approved", "effective", "superseded", "annulled"],
                    )
                ),
                name="process_version_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("objective", ""), _negated=True),
                    models.Q(("scope", ""), _negated=True),
                ),
                name="process_version_text_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_hash__regex", "^[0-9a-f]{64}$")),
                name="process_version_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="processversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="process_version_dates_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="sipocentry",
            index=models.Index(
                fields=["process_version", "entry_type", "position"], name="sipoc_section_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="sipocentry",
            constraint=models.UniqueConstraint(
                fields=("process_version", "entry_type", "position"), name="sipoc_type_position_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sipocentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="sipoc_position_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="sipocentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry_type__in", ["supplier", "input", "activity", "output", "customer"])
                ),
                name="sipoc_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="sipocentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True), name="sipoc_name_ck"
            ),
        ),
    ]
