# Generated by Django 5.2.17 on 2026-08-21 01:15

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500)),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('policy', 'Política'), ('procedure', 'Procedimiento'), ('instruction', 'Instructivo'), ('form', 'Formato'), ('record', 'Registro'), ('other', 'Otro')], max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deactivated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.organization')),
                ('responsible_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_documents', to='organizations.area')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=150)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pendiente'), ('clean', 'Limpio'), ('rejected', 'Rechazado'), ('error', 'Error')], default='pending', max_length=20)),
                ('synthetic_confirmed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_file_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('effective', 'Vigente'), ('superseded', 'Sustituido'), ('annulled', 'Anulado')], max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('version_hash', models.CharField(max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('file_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to='documents.fileasset')),
            ],
            options={
                'db_table': 'documents_document_version',
                'ordering': ['document__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500)),
                ('code', models.CharField(max_length=50)),
                ('issuer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('reference_type', models.CharField(choices=[('law', 'Ley'), ('regulation', 'Reglamento'), ('standard', 'Norma técnica'), ('guideline', 'Guía'), ('internal', 'Referencia interna')], max_length=30)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deactivated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_reference_source',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobado'), ('effective', 'Vigente'), ('superseded', 'Sustituido'), ('annulled', 'Anulado')], max_length=30)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('consulted_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reference_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.referencesource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_versions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_versions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_reference_version',
                'ordering': ['reference_source__code', '-version_no'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'responsible_area', 'is_active'], name='doc_catalog_ix'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='doc_scope_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('deactivation_reason', ''), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False), models.Q(('deactivation_reason', ''), _negated=True)), _connector='OR'), name='doc_lifecycle_ck'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('title', ''), _negated=True)), name='doc_required_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('document_type__in', ['policy', 'procedure', 'instruction', 'form', 'record', 'other'])), name='doc_type_ck'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['sha256'], name='doc_file_hash_ix'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='doc_file_size_ck'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='doc_file_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('scan_status__in', ['pending', 'clean', 'rejected', 'error'])), name='doc_file_scan_ck'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.CheckConstraint(condition=models.Q(('synthetic_confirmed', True)), name='doc_file_synthetic_ck'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'status', '-version_no'], name='doc_version_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_no'), name='doc_version_no_uq'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='doc_version_no_ck'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'effective', 'superseded', 'annulled'])), name='doc_version_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='doc_version_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('file_asset__isnull', True), models.Q(('content', ''), _negated=True)), models.Q(('file_asset__isnull', False), ('content', '')), _connector='OR'), name='doc_version_payload_ck'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_hash__regex', '^[0-9a-f]{64}$')), name='doc_version_hash_ck'),
        ),
        migrations.AddConstraint(
            model_name='referencesource',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='ref_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='referencesource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('deactivation_reason', ''), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False), models.Q(('deactivation_reason', ''), _negated=True)), _connector='OR'), name='ref_lifecycle_ck'),
        ),
        migrations.AddConstraint(
            model_name='referencesource',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('issuer', ''), _negated=True), models.Q(('title', ''), _negated=True)), name='ref_required_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='referencesource',
            constraint=models.CheckConstraint(condition=models.Q(('reference_type__in', ['law', 'regulation', 'standard', 'guideline', 'internal'])), name='ref_type_ck'),
        ),
        migrations.AddIndex(
            model_name='referenceversion',
            index=models.Index(fields=['reference_source', 'status', '-version_no'], name='ref_version_state_ix'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.UniqueConstraint(fields=('reference_source', 'version_no'), name='ref_version_no_uq'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='ref_version_no_ck'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'effective', 'superseded', 'annulled'])), name='ref_version_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='ref_version_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.CheckConstraint(condition=models.Q(('summary', ''), _negated=True), name='ref_summary_ck'),
        ),
        migrations.AddConstraint(
            model_name='referenceversion',
            constraint=models.CheckConstraint(condition=models.Q(('content_hash__isnull', True), ('content_hash__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='ref_content_hash_ck'),
        ),
    ]
