# Generated by Django 5.2.17 on 2026-08-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='processes.process'),
        ),
    ]
