# Generated by Django 5.2.17 on 2026-08-21 15:07

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0002_remove_finding_audit_finding_status_ck_and_more'),
        ('improvements', '0001_initial'),
        ('indicators', '0001_initial'),
        ('organizations', '0001_initial'),
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls_deactivated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_controls', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_control',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControlVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('effective', 'Vigente'), ('superseded', 'Sustituida'), ('annulled', 'Anulada')], default='draft', max_length=20)),
                ('description', models.TextField()),
                ('control_type', models.CharField(choices=[('preventive', 'Preventivo'), ('detective', 'Detectivo'), ('corrective', 'Correctivo')], max_length=20)),
                ('frequency', models.CharField(choices=[('continuous', 'Continuo'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='risks.control')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_versions_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_control_version',
                'ordering': ['control__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('cause', models.TextField()),
                ('event', models.TextField()),
                ('consequence', models.TextField()),
                ('status', models.CharField(choices=[('identified', 'Identificado'), ('assessed', 'Evaluado'), ('under_treatment', 'En tratamiento'), ('controlled', 'Controlado'), ('accepted', 'Aceptado'), ('closed', 'Cerrado'), ('reopened', 'Reabierto')], default='identified', max_length=30)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='processes.process')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RiskActionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='improvements.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_links', to='risks.risk')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk_action',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revisión'), ('approved', 'Aprobada'), ('superseded', 'Sustituida')], default='draft', max_length=20)),
                ('probability', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('inherent_level', models.PositiveSmallIntegerField()),
                ('inherent_band', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20)),
                ('residual_probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_impact', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_band', models.CharField(blank=True, choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20)),
                ('assessed_at', models.DateTimeField()),
                ('next_review_date', models.DateField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='risks.risk')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments_submitted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk_assessment',
                'ordering': ['risk__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('effectiveness_expected', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], max_length=20)),
                ('control_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_controls', to='risks.controlversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_controls', to='risks.risk')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk_control',
                'ordering': ['risk__code', 'control_version__control__code'],
            },
        ),
        migrations.CreateModel(
            name='ControlReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField()),
                ('result', models.CharField(choices=[('effective', 'Eficaz'), ('partially_effective', 'Parcialmente eficaz'), ('ineffective', 'Ineficaz')], max_length=30)),
                ('notes', models.TextField()),
                ('next_review_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('risk_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='risks.riskcontrol')),
            ],
            options={
                'db_table': 'risks_control_review',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFindingLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='audits.finding')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_links', to='risks.risk')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk_finding',
            },
        ),
        migrations.CreateModel(
            name='RiskIndicatorLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='indicators.indicator')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_links', to='risks.risk')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risks_risk_indicator',
            },
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='control_scope_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deactivated_at__isnull', True), ('deactivated_by__isnull', True), ('deactivation_reason', ''), ('is_active', True)), models.Q(('deactivated_at__isnull', False), ('deactivated_by__isnull', False), ('is_active', False), models.Q(('deactivation_reason', ''), _negated=True)), _connector='OR'), name='control_lifecycle_ck'),
        ),
        migrations.AddConstraint(
            model_name='control',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('name', ''), _negated=True)), name='control_required_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='controlversion',
            constraint=models.UniqueConstraint(fields=('control', 'version_no'), name='control_version_no_uq'),
        ),
        migrations.AddConstraint(
            model_name='controlversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='control_version_no_ck'),
        ),
        migrations.AddConstraint(
            model_name='controlversion',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'effective', 'superseded', 'annulled'])), name='control_version_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='controlversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='control_version_dates_ck'),
        ),
        migrations.AddConstraint(
            model_name='controlversion',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='control_version_text_ck'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['organization', 'process', 'status'], name='risk_catalog_ix'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.UniqueConstraint(models.F('organization'), django.db.models.functions.text.Lower('code'), name='risk_scope_code_ci_uq'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['identified', 'assessed', 'under_treatment', 'controlled', 'accepted', 'closed', 'reopened'])), name='risk_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code', ''), _negated=True), models.Q(('cause', ''), _negated=True), models.Q(('event', ''), _negated=True), models.Q(('consequence', ''), _negated=True)), name='risk_required_text_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskactionlink',
            constraint=models.UniqueConstraint(fields=('risk', 'action'), name='risk_action_link_uq'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk', 'status', '-version_no'], name='risk_assessment_state_ix'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['status', 'next_review_date'], name='risk_review_alert_ix'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(fields=('risk', 'version_no'), name='risk_assessment_version_uq'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gte', 1)), name='risk_assessment_version_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', 1), ('probability__lte', 5)), name='risk_probability_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('impact__gte', 1), ('impact__lte', 5)), name='risk_impact_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('inherent_level', django.db.models.expressions.CombinedExpression(models.F('probability'), '*', models.F('impact')))), name='risk_inherent_product_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('residual_band', ''), ('residual_impact__isnull', True), ('residual_level__isnull', True), ('residual_probability__isnull', True)), models.Q(('residual_impact__gte', 1), ('residual_impact__lte', 5), ('residual_level', django.db.models.expressions.CombinedExpression(models.F('residual_probability'), '*', models.F('residual_impact'))), ('residual_probability__gte', 1), ('residual_probability__lte', 5)), _connector='OR'), name='risk_residual_complete_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_review', 'approved', 'superseded'])), name='risk_assessment_status_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskcontrol',
            constraint=models.UniqueConstraint(fields=('risk', 'control_version', 'valid_from'), name='risk_control_period_uq'),
        ),
        migrations.AddConstraint(
            model_name='riskcontrol',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='risk_control_dates_ck'),
        ),
        migrations.AddIndex(
            model_name='controlreview',
            index=models.Index(fields=['next_review_date'], name='control_review_alert_ix'),
        ),
        migrations.AddConstraint(
            model_name='controlreview',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['effective', 'partially_effective', 'ineffective'])), name='control_review_result_ck'),
        ),
        migrations.AddConstraint(
            model_name='controlreview',
            constraint=models.CheckConstraint(condition=models.Q(('notes', ''), _negated=True), name='control_review_notes_ck'),
        ),
        migrations.AddConstraint(
            model_name='riskfindinglink',
            constraint=models.UniqueConstraint(fields=('risk', 'finding'), name='risk_finding_link_uq'),
        ),
        migrations.AddConstraint(
            model_name='riskindicatorlink',
            constraint=models.UniqueConstraint(fields=('risk', 'indicator'), name='risk_indicator_link_uq'),
        ),
    ]
