# Generated by Django 5.2.17 on 2026-08-21 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('correlation_id', models.UUIDField()),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('success', 'Correcto'), ('denied', 'Denegado'), ('error', 'Error'), ('cancelled', 'Cancelado')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditlog_event',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id', '-occurred_at'], name='audit_obj_time_ix'), models.Index(fields=['correlation_id', 'occurred_at'], name='audit_corr_time_ix')],
                'constraints': [models.CheckConstraint(condition=models.Q(('result__in', ['success', 'denied', 'error', 'cancelled'])), name='audit_result_ck'), models.CheckConstraint(condition=models.Q(('event_hash__regex', '^[0-9a-f]{64}$')), name='audit_hash_ck'), models.CheckConstraint(condition=models.Q(models.Q(('object_type', ''), _negated=True), models.Q(('action', ''), _negated=True)), name='audit_required_ck')],
            },
        ),
    ]
