# Generated by Django 5.2.17 on 2026-08-21 03:01

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_document_process"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Recibida"),
                            ("validating", "Validando"),
                            ("rejected", "Rechazada"),
                            ("accepted", "Aceptada"),
                            ("processed", "Procesada"),
                            ("duplicate", "Duplicada"),
                            ("failed", "Fallida"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_hash", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_attempts",
                        to="imports.importjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retry_attempts",
                        to="imports.importjob",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to="documents.fileasset",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "imports_import_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField()),
                ("normalized_hash", models.CharField(max_length=64)),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="imports.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "imports_import_row",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ImportError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("column_name", models.CharField(blank=True, max_length=100)),
                ("rule_code", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[("blocking", "Bloqueante"), ("warning", "Advertencia")],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("suggested_action", models.CharField(blank=True, max_length=500)),
                (
                    "import_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="errors",
                        to="imports.importrow",
                    ),
                ),
            ],
            options={
                "db_table": "imports_import_error",
                "ordering": ["import_row__row_number", "column_name", "rule_code"],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("kpi_observations", "Observaciones KPI"),
                            ("audit_findings", "Hallazgos de auditoría"),
                            ("corrective_actions", "Acciones correctivas"),
                            ("risks", "Riesgos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imports_template_deactivated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_templates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "imports_template",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ImportTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_no", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_review", "En revisión"),
                            ("effective", "Vigente"),
                            ("superseded", "Sustituida"),
                            ("annulled", "Anulada"),
                        ],
                        max_length=30,
                    ),
                ),
                ("schema_definition", models.JSONField()),
                ("schema_hash", models.CharField(max_length=64)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_template_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_template_versions",
                        to="documents.fileasset",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_template_versions_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="imports.importtemplate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "imports_template_version",
                "ordering": ["template__code", "-version_no"],
            },
        ),
        migrations.AddField(
            model_name="importjob",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_jobs",
                to="imports.importtemplateversion",
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["import_job", "is_valid", "row_number"], name="import_row_validation_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("import_job", "row_number"), name="import_row_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(("normalized_hash__regex", "^[0-9a-f]{64}$")),
                name="import_row_hash_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="importerror",
            index=models.Index(fields=["import_row", "severity"], name="import_error_row_ix"),
        ),
        migrations.AddConstraint(
            model_name="importerror",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity__in", ["blocking", "warning"])),
                name="import_error_severity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importerror",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rule_code", ""), _negated=True),
                    models.Q(("message", ""), _negated=True),
                ),
                name="import_error_text_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplate",
            index=models.Index(
                fields=["organization", "is_active", "code"], name="import_template_catalog_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplate",
            constraint=models.UniqueConstraint(
                models.F("organization"),
                django.db.models.functions.text.Lower("code"),
                name="import_template_scope_code_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("deactivated_at__isnull", True),
                        ("deactivated_by__isnull", True),
                        ("deactivation_reason", ""),
                        ("is_active", True),
                    ),
                    models.Q(
                        ("deactivated_at__isnull", False),
                        ("deactivated_by__isnull", False),
                        ("is_active", False),
                        models.Q(("deactivation_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="import_template_lifecycle_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        ["kpi_observations", "audit_findings", "corrective_actions", "risks"],
                    )
                ),
                name="import_template_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("code", ""), _negated=True), models.Q(("name", ""), _negated=True)
                ),
                name="import_template_text_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="importtemplateversion",
            index=models.Index(
                fields=["template", "status", "-version_no"], name="imp_tpl_ver_state_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version_no"), name="import_template_version_no_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_no__gte", 1)), name="import_template_version_no_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "in_review", "effective", "superseded", "annulled"])
                ),
                name="import_template_version_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_hash__regex", "^[0-9a-f]{64}$")),
                name="import_template_schema_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="import_template_version_dates_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["organization", "status", "-created_at"], name="import_job_queue_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["organization", "file_hash"], name="import_job_hash_ix"),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "received",
                            "validating",
                            "rejected",
                            "accepted",
                            "processed",
                            "duplicate",
                            "failed",
                        ],
                    )
                ),
                name="import_job_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("file_hash__regex", "^[0-9a-f]{64}$")),
                name="import_job_file_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__gte", 1)), name="import_job_attempt_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["accepted", "processed"])),
                fields=("organization", "file_hash"),
                name="import_job_accepted_file_uq",
            ),
        ),
    ]
