# Generated by Django 5.2.17 on 2026-08-29 17:45

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("indicators", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("version_no", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("descriptive", "Descriptivos y atípicos"),
                            ("pareto", "Pareto por servicio"),
                            ("control_chart", "Gráfico de control"),
                            ("moving_average", "Tendencia y media móvil"),
                            ("linear_regression", "Regresión lineal"),
                            ("logistic_regression", "Regresión logística"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parameters", models.JSONField(blank=True)),
                ("parameters_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("superseded", "Sustituida"),
                            ("annulled", "Anulada"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_definitions_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_definitions",
                        to="indicators.indicator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_definition",
                "ordering": ["code", "-version_no"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("executed_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completada"),
                            ("rejected_quality", "Rechazada por calidad"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_count", models.PositiveIntegerField()),
                ("train_count", models.PositiveIntegerField(default=0)),
                ("test_count", models.PositiveIntegerField(default=0)),
                ("input_hash", models.CharField(max_length=64)),
                ("output_hash", models.CharField(max_length=64)),
                ("metrics", models.JSONField(blank=True)),
                ("assumptions", models.JSONField()),
                ("result", models.JSONField()),
                ("quality_gate_passed", models.BooleanField()),
                ("synthetic_confirmed", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="analytics.analysisdefinition",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_runs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_run",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analysisdefinition",
            index=models.Index(
                fields=["status", "analysis_type", "code"], name="analytics_catalog_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.UniqueConstraint(
                fields=("code", "version_no"), name="analytics_code_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("version_no"),
                name="analytics_code_version_ci_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_no__gte", 1)), name="analytics_version_no_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "analysis_type__in",
                        [
                            "descriptive",
                            "pareto",
                            "control_chart",
                            "moving_average",
                            "linear_regression",
                            "logistic_regression",
                        ],
                    )
                ),
                name="analytics_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "published", "superseded", "annulled"])
                ),
                name="analytics_definition_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("parameters_hash__regex", "^[0-9a-f]{64}$")),
                name="analytics_parameters_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("status", "published"),
                    ),
                    models.Q(
                        models.Q(("status", "published"), _negated=True),
                        ("published_at__isnull", True),
                        ("published_by__isnull", True),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by__isnull", False),
                        ("status__in", ["superseded", "annulled"]),
                    ),
                    _connector="OR",
                ),
                name="analytics_publication_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="analysisrun",
            index=models.Index(
                fields=["definition", "-executed_at"], name="analytics_run_history_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["completed", "rejected_quality"])),
                name="analytics_run_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_count__gte", 1)), name="analytics_run_input_count_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_end__isnull", True),
                    ("period_end__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="analytics_run_dates_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_hash__regex", "^[0-9a-f]{64}$")),
                name="analytics_input_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_hash__regex", "^[0-9a-f]{64}$")),
                name="analytics_output_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("synthetic_confirmed", True)), name="analytics_synthetic_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quality_gate_passed", True), ("status", "completed")),
                    models.Q(("quality_gate_passed", False), ("status", "rejected_quality")),
                    _connector="OR",
                ),
                name="analytics_quality_status_ck",
            ),
        ),
    ]
